const font_list = [
	{ value: 'Roboto, sans-serif', name: 'Roboto' },
{ value: 'Zilla Slab Highlight, cursive', name: 'Zilla Slab Highlight' },
{ value: 'Open Sans, sans-serif', name: 'Open Sans' },
{ value: 'Spectral, serif', name: 'Spectral' },
{ value: 'Slabo 27px, serif', name: 'Slabo 27px' },
{ value: 'Lato, sans-serif', name: 'Lato' },
{ value: 'Roboto Condensed, sans-serif', name: 'Roboto Condensed' },
{ value: 'Oswald, sans-serif', name: 'Oswald' },
{ value: 'Source Sans Pro, sans-serif', name: 'Source Sans Pro' },
{ value: 'Raleway, sans-serif', name: 'Raleway' },
{ value: 'Zilla Slab, serif', name: 'Zilla Slab' },
{ value: 'Montserrat, sans-serif', name: 'Montserrat' },
{ value: 'PT Sans, sans-serif', name: 'PT Sans' },
{ value: 'Roboto Slab, serif', name: 'Roboto Slab' },
{ value: 'Merriweather, serif', name: 'Merriweather' },
{ value: 'Saira Condensed, sans-serif', name: 'Saira Condensed' },
{ value: 'Saira, sans-serif', name: 'Saira' },
{ value: 'Open Sans Condensed, sans-serif', name: 'Open Sans Condensed' },
{ value: 'Saira Semi Condensed, sans-serif', name: 'Saira Semi Condensed' },
{ value: 'Saira Extra Condensed, sans-serif', name: 'Saira Extra Condensed' },
{ value: 'Julee, cursive', name: 'Julee' },
{ value: 'Archivo, sans-serif', name: 'Archivo' },
{ value: 'Ubuntu, sans-serif', name: 'Ubuntu' },
{ value: 'Lora, serif', name: 'Lora' },
{ value: 'Manuale, serif', name: 'Manuale' },
{ value: 'Asap Condensed, sans-serif', name: 'Asap Condensed' },
{ value: 'Faustina, serif', name: 'Faustina' },
{ value: 'Cairo, sans-serif', name: 'Cairo' },
{ value: 'Playfair Display, serif', name: 'Playfair Display' },
{ value: 'Droid Serif, serif', name: 'Droid Serif' },
{ value: 'Noto Sans, sans-serif', name: 'Noto Sans' },
{ value: 'PT Serif, serif', name: 'PT Serif' },
{ value: 'Droid Sans, sans-serif', name: 'Droid Sans' },
{ value: 'Arimo, sans-serif', name: 'Arimo' },
{ value: 'Poppins, sans-serif', name: 'Poppins' },
{ value: 'Sedgwick Ave Display, cursive', name: 'Sedgwick Ave Display' },
{ value: 'Titillium Web, sans-serif', name: 'Titillium Web' },
{ value: 'Muli, sans-serif', name: 'Muli' },
{ value: 'Sedgwick Ave, cursive', name: 'Sedgwick Ave' },
{ value: 'Indie Flower, cursive', name: 'Indie Flower' },
{ value: 'Mada, sans-serif', name: 'Mada' },
{ value: 'PT Sans Narrow, sans-serif', name: 'PT Sans Narrow' },
{ value: 'Noto Serif, serif', name: 'Noto Serif' },
{ value: 'Bitter, serif', name: 'Bitter' },
{ value: 'Dosis, sans-serif', name: 'Dosis' },
{ value: 'Josefin Sans, sans-serif', name: 'Josefin Sans' },
{ value: 'Inconsolata, monospace', name: 'Inconsolata' },
{ value: 'Bowlby One SC, cursive', name: 'Bowlby One SC' },
{ value: 'Oxygen, sans-serif', name: 'Oxygen' },
{ value: 'Arvo, serif', name: 'Arvo' },
{ value: 'Hind, sans-serif', name: 'Hind' },
{ value: 'Cabin, sans-serif', name: 'Cabin' },
{ value: 'Fjalla One, sans-serif', name: 'Fjalla One' },
{ value: 'Anton, sans-serif', name: 'Anton' },
{ value: 'Cairo, sans-serif', name: 'Cairo' },
{ value: 'Playfair Display, serif', name: 'Playfair Display' },
{ value: 'Droid Serif, serif', name: 'Droid Serif' },
{ value: 'Noto Sans, sans-serif', name: 'Noto Sans' },
{ value: 'PT Serif, serif', name: 'PT Serif' },
{ value: 'Droid Sans, sans-serif', name: 'Droid Sans' },
{ value: 'Arimo, sans-serif', name: 'Arimo' },
{ value: 'Poppins, sans-serif', name: 'Poppins' },
{ value: 'Sedgwick Ave Display, cursive', name: 'Sedgwick Ave Display' },
{ value: 'Titillium Web, sans-serif', name: 'Titillium Web' },
{ value: 'Muli, sans-serif', name: 'Muli' },
{ value: 'Sedgwick Ave, cursive', name: 'Sedgwick Ave' },
{ value: 'Indie Flower, cursive', name: 'Indie Flower' },
{ value: 'Mada, sans-serif', name: 'Mada' },
{ value: 'PT Sans Narrow, sans-serif', name: 'PT Sans Narrow' },
{ value: 'Noto Serif, serif', name: 'Noto Serif' },
{ value: 'Bitter, serif', name: 'Bitter' },
{ value: 'Dosis, sans-serif', name: 'Dosis' },
{ value: 'Josefin Sans, sans-serif', name: 'Josefin Sans' },
{ value: 'Inconsolata, monospace', name: 'Inconsolata' },
{ value: 'Bowlby One SC, cursive', name: 'Bowlby One SC' },
{ value: 'Oxygen, sans-serif', name: 'Oxygen' },
{ value: 'Arvo, serif', name: 'Arvo' },
{ value: 'Hind, sans-serif', name: 'Hind' },
{ value: 'Cabin, sans-serif', name: 'Cabin' },
{ value: 'Fjalla One, sans-serif', name: 'Fjalla One' },
{ value: 'Anton, sans-serif', name: 'Anton' },
{ value: 'Acme, sans-serif', name: 'Acme' },
{ value: 'Archivo Narrow, sans-serif', name: 'Archivo Narrow' },
{ value: 'Mukta Vaani, sans-serif', name: 'Mukta Vaani' },
{ value: 'Play, sans-serif', name: 'Play' },
{ value: 'Cuprum, sans-serif', name: 'Cuprum' },
{ value: 'Maven Pro, sans-serif', name: 'Maven Pro' },
{ value: 'EB Garamond, serif', name: 'EB Garamond' },
{ value: 'Passion One, cursive', name: 'Passion One' },
{ value: 'Ropa Sans, sans-serif', name: 'Ropa Sans' },
{ value: 'Francois One, sans-serif', name: 'Francois One' },
{ value: 'Archivo Black, sans-serif', name: 'Archivo Black' },
{ value: 'Pathway Gothic One, sans-serif', name: 'Pathway Gothic One' },
{ value: 'Exo, sans-serif', name: 'Exo' },
{ value: 'Vollkorn, serif', name: 'Vollkorn' },
{ value: 'Libre Franklin, sans-serif', name: 'Libre Franklin' },
{ value: 'Crete Round, serif', name: 'Crete Round' },
{ value: 'Alegreya, serif', name: 'Alegreya' },
{ value: 'PT Sans Caption, sans-serif', name: 'PT Sans Caption' },
{ value: 'Alegreya Sans, sans-serif', name: 'Alegreya Sans' },
{ value: 'Source Code Pro, monospace', name: 'Source Code Pro' },

]

export default font_list